name: Deploy Cerver to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Paso opcional: Limpiar el mensaje del commit (quitar espacios o caracteres raros)
      - name: Get commit message
        id: vars
        run: echo "commit_msg=$(echo ${GITHUB_EVENT_PULL_REQUEST_TITLE:-${{ github.event.head_commit.message }}} | tr -dc '[:alnum:]\n\r' | tr ' ' '-' | cut -c1-50)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cerver:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cerver:${{ github.sha }}
